In [ ]:
#Matrix
mat<-matrix(c(1, 2,3,4,5,6,7,8,9,10), nrow=5, ncol=2)
print(mat)

     [,1] [,2]
[1,]    1    6
[2,]    2    7
[3,]    3    8
[4,]    4    9
[5,]    5   10


In [ ]:
#using this we can access a perticuler element from given matrix
#first value is for row and the second for column
print(mat[1,2])

[1] 6


In [ ]:
#to show whole row of given matrix
print(mat[1,])   #row 1 has two element 1,6

[1] 1 6


In [ ]:
#to show whole column of given matrix

print(mat[,2])  #column 2 has 5 element(6,7,8,9,10)

[1]  6  7  8  9 10


In [ ]:
#to show more than 1 row
print(mat[c(1,2,3),])  #row 1,2,3 has elements respectively (1,6),(2,7),(3,8)

     [,1] [,2]
[1,]    1    6
[2,]    2    7
[3,]    3    8


In [ ]:
#to show more than 1 column
print(mat[,c(1,2)])  #column 1,2 has whole number so it print all

     [,1] [,2]
[1,]    1    6
[2,]    2    7
[3,]    3    8
[4,]    4    9
[5,]    5   10


In [ ]:
#to show a peticuler row with column

print(mat[c(1,2),1])  #row 1,2 has ele,ent 1,2

[1] 1 2


In [ ]:
#matrix operations
#add rows and columns

#for adding row
print(rbind(mat,c(10,20)))

#for adding columns
mat<-cbind(mat,c(11,12,13,14,15))
print(mat)


     [,1] [,2]
[1,]    1    6
[2,]    2    7
[3,]    3    8
[4,]    4    9
[5,]    5   10
[6,]   10   20
     [,1] [,2] [,3]
[1,]    1    6   11
[2,]    2    7   12
[3,]    3    8   13
[4,]    4    9   14
[5,]    5   10   15


In [ ]:
#Deletion in matrix

mat<-mat[-c(5),-c(3)] #whole row and columns is deleted
print(mat)

     [,1] [,2]
[1,]    1    6
[2,]    2    7
[3,]    3    8
[4,]    4    9


In [ ]:
#deletion of whole row only
mat<-mat[-c(1),]
print(mat)

#deletion of whole columns only
mat<-mat[,-c(2)]
print(mat)

     [,1] [,2]
[1,]    2    7
[2,]    3    8
[3,]    4    9
[1] 2 3 4


In [ ]:
#Searching matrix
matC<-matrix(c(10, 20,30,40,50,60,70,80,90,100,110,120), nrow=3, ncol=4)
print(matC)

ch<-readline("Searching Element is :")
print(ch %in% matC)

     [,1] [,2] [,3] [,4]
[1,]   10   40   70  100
[2,]   20   50   80  110
[3,]   30   60   90  120
Searching Element is :130
[1] FALSE


In [ ]:
#searching using for loop
c<-readline("Enter searching element: ")
k<-0
for (i in matC){
  if (i==c){
      k<-k+1
      break
  }
}
if(k==1){
  cat("True")
}else{
  cat("False")
}

Enter searching element: 30
True

In [ ]:
#Check Dimension of a matrix
print(dim(matC))

[1] 3 4


In [ ]:
#Checking the length of a matrix
length(matC) #it show total number of element

[1] 12

In [ ]:
#Checking number of rows and columns
nrow(matC)
ncol(matC)

[1] 3

[1] 4

In [ ]:
#Print single element of a matrix
for(r in 1:nrow(matC)){  #it is row and columns vise
  for (c in 1:ncol(matC)){
    print(matC[r,c])
  }
}

[1] 10
[1] 40
[1] 70
[1] 100
[1] 20
[1] 50
[1] 80
[1] 110
[1] 30
[1] 60
[1] 90
[1] 120


In [ ]:
#it is element vise
for (i in matC){
  print(i)
}

[1] 10
[1] 20
[1] 30
[1] 40
[1] 50
[1] 60
[1] 70
[1] 80
[1] 90
[1] 100
[1] 110
[1] 120


In [ ]:
#Combine two matirx together
m<-matrix(c(10,20,30,40,50,60),nrow=3,ncol = 2)
n<-matrix(c(1,2,3,4,5,6),nrow=3,ncol = 2)
res<-cbind(m,n)
print(res)
res1<-rbind(m,n)
print(res1)

     [,1] [,2] [,3] [,4]
[1,]   10   40    1    4
[2,]   20   50    2    5
[3,]   30   60    3    6
     [,1] [,2]
[1,]   10   40
[2,]   20   50
[3,]   30   60
[4,]    1    4
[5,]    2    5
[6,]    3    6


In [ ]:
#Arithmetic operation between two matrixes
print(m+n)
print(m*n)
print(m/n)
print(m%%n)
print(m^(n/2))

     [,1] [,2]
[1,]   11   44
[2,]   22   55
[3,]   33   66
     [,1] [,2]
[1,]   10  160
[2,]   40  250
[3,]   90  360
     [,1] [,2]
[1,]   10   10
[2,]   10   10
[3,]   10   10
     [,1] [,2]
[1,]    0    0
[2,]    0    0
[3,]    0    0
           [,1]      [,2]
[1,]   3.162278   1600.00
[2,]  20.000000  17677.67
[3,] 164.316767 216000.00


In [ ]:
#Array and its operations

In [ ]:
#Single Dimension Array
arr<-array(c(10,20,30,40,50,60,70,80,90,100,110,120))
print(arr)

#Multi Dimension Array
arr1<-array(c(10,20,30,40,50,60,70,80,90,100,110,120),dim =c (2,2,3))
print(arr)

 [1]  10  20  30  40  50  60  70  80  90 100 110 120
 [1]  10  20  30  40  50  60  70  80  90 100 110 120


In [ ]:
#Accessing Elements of Array
#print element using multi dimension indexx
print(arr1[1,2,1])

#print element of whole rows
print(arr1[c(1), ,1])

#print element of whole columns
print(arr1[,c(2),2])

[1] 30
[1] 10 30
[1] 70 80


In [ ]:


# Append a new element to the end of an array
arr <- c(1, 2, 3, 4, 5)
arr <- append(arr, 6)
print(arr)

# Append a vector to the end of an array
arr <- c(1, 2, 3, 4, 5)
new_elements <- c(6, 7, 8)
arr <- append(arr, new_elements)
print(arr)

# Append an array to the end of another array
arr1 <- c(1, 2, 3, 4, 5)
arr2 <- c(6, 7, 8, 9, 10)
arr <- append(arr1, arr2,after = 1)
print(arr)


[1] 1 2 3 4 5 6
[1] 1 2 3 4 5 6 7 8
 [1]  1  6  7  8  9 10  2  3  4  5


In [ ]:
# prompt: append() in multi dimension array

# Append a new element to the end of a multi-dimensional array
arr <- array(c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12), dim = c(2, 2, 3))
new_element <- c(13, 14, 15)
arr <- append(arr, new_element, after = 2)
print(arr)

# Append a vector to the end of a multi-dimensional array
arr <- array(c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12), dim = c(2, 2, 3))
new_elements <- c(13, 14, 15, 16, 17, 18)
arr <- append(arr, new_elements, after = 2)
print(arr)

# Append an array to the end of another multi-dimensional array
arr1 <- array(c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12), dim = c(2, 2, 3))
arr2 <- array(c(13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24), dim = c(2, 3, 2))
arr <- append(arr1, arr2, after = 2)
print(arr)


 [1]  1  2 13 14 15  3  4  5  6  7  8  9 10 11 12
 [1]  1  2 13 14 15 16 17 18  3  4  5  6  7  8  9 10 11 12
 [1]  1  2 13 14 15 16 17 18 19 20 21 22 23 24  3  4  5  6  7  8  9 10 11 12


In [ ]:
#Array operations using apply() function
arr5<-array(c(1,2,3,4,5,6),dim=c(2,3))
res<-apply(arr5,c(1,2),sum)
res

res<-apply(arr5,c(1),max)  # c(1) for rows , c(2) for columns
res


[,1] [,2] [,3]
[1,] 1    3    5   
[2,] 2    4    6

[1] 5 6

In [37]:
#search elements using %in% operator
res<-3 %in% arr5
print(res)

[1] TRUE


In [38]:
#it is similer to the matrix, you can find dimensions using dim() function

print(dim(arr5))

[1] 2 3


In [39]:
#to print individual elements from array
for (i in arr5){
  print(i)
}

[1] 1
[1] 2
[1] 3
[1] 4
[1] 5
[1] 6


In [42]:
#combine two arrays
ar1<-array(c(10,20,30,40,50,60),dim=c(2,3))
ar2<-array(c(1,2,3,4,5,6),dim=c(2,3))

print(rbind(ar1,ar2))

#if i give input from out of index
ar1<-array(c(10,20,30,40,50,60),dim=c(2,3))
ar2<-array(c(1,2,3,4,5,6,7,8,9,10,11,12),dim=c(3,4))
print(rbind(ar1,ar2))



     [,1] [,2] [,3]
[1,]   10   30   50
[2,]   20   40   60
[3,]    1    3    5
[4,]    2    4    6


ERROR: Error in rbind(ar1, ar2): number of columns of matrices must match (see arg 2)


In [49]:
#it means if I bind using row we need same rows number in each or same as columns
ar1<-array(c(10,20,30,40,50,60),dim=c(2,3))
ar2<-array(c(1,2,3,4,5,6,7,8,9,10,11,12),dim=c(4,3))
res<-rbind(ar1,ar2)
print(res)


#for columns
ar3<-array(c(11,22,33,44,55,66,77,88,99,110,120),dim = c(6,2))
print(cbind(res,ar3))

#all numbers combine properly

     [,1] [,2] [,3]
[1,]   10   30   50
[2,]   20   40   60
[3,]    1    5    9
[4,]    2    6   10
[5,]    3    7   11
[6,]    4    8   12
     [,1] [,2] [,3] [,4] [,5]
[1,]   10   30   50   11   77
[2,]   20   40   60   22   88
[3,]    1    5    9   33   99
[4,]    2    6   10   44  110
[5,]    3    7   11   55  120
[6,]    4    8   12   66   11
